/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-01-27 14:43:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberspage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<title>Gray</title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\" />\r\n");
      out.write("<!-- Font Awesome icons (free version)-->\r\n");
      out.write("<!-- Google fonts-->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Varela+Round\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Masthead-->\r\n");
      out.write("\t<header class=\"header\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Navigation-->\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg navbar-light fixed-top\"\r\n");
      out.write("\t\t\tid=\"mainNav\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand js-scroll-trigger\" href=\"#page-top\">Start</a>\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler navbar-toggler-right\" type=\"button\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#navbarResponsive\"\r\n");
      out.write("\t\t\t\t\taria-controls=\"navbarResponsive\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t\tMenu <i class=\"fas fa-bars\"></i>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<form action=\"trafficcontrol\" method = \"get\">\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">Submit</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#about\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#projects\">Projects</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#signup\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- About-->\r\n");
      out.write("\t<section class=\"about-section text-center\" id=\"about\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t<img class = \"img-fluid img-thumbnail\" alt=\"profile-img\" src=\"assets/img/alice.png\">\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<h4 class = \"text-white-50 mx-auto mt-2 mb-5\">Alice Wonder</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p class=\"text-white-50 mx-auto mt-2 mb-5\"> A lucid dream is a type of dream where the\r\n");
      out.write("\t\t\t\t\tdreamer becomes aware that they are dreaming. During a lucid dream,\r\n");
      out.write("\t\t\t\t\tthe dreamer may gain some amount of control over the dream\r\n");
      out.write("\t\t\t\t\tcharacters, narrative, and environment; however, this is not\r\n");
      out.write("\t\t\t\t\tactually necessary for a dream to be described as\r\n");
      out.write("\t\t\t\t\tlucid.[1][2][3][4] Lucid dreaming has been studied and reported for\r\n");
      out.write("\t\t\t\t\tmany years. Prominent figures from ancient to modern times have\r\n");
      out.write("\t\t\t\t\tbeen fascinated by lucid dreams and have sought ways to better\r\n");
      out.write("\t\t\t\t\tunderstand their causes and purpose. Many different theories have\r\n");
      out.write("\t\t\t\t\temerged as a result of scientific research on the subject and have\r\n");
      out.write("\t\t\t\t\teven been shown in pop culture. Further developments in\r\n");
      out.write("\t\t\t\t\tpsychological research have pointed to ways in which this form of\r\n");
      out.write("\t\t\t\t\tdreaming may be utilized as a form of sleep therapy. There are two\r\n");
      out.write("\t\t\t\t\tmeans of initiating a lucid dream:</p>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<p>Source: <a href=\"https://en.wikipedia.org/wiki/Lucid_dream\">Wikipedia</a> </p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Signup-->\r\n");
      out.write("\t<section class=\"signup-section\" id=\"signup\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-10 col-lg-8 mx-auto text-center\">\r\n");
      out.write("\t\t\t\t\t<i class=\"far fa-paper-plane fa-2x mb-2 text-white\"></i>\r\n");
      out.write("\t\t\t\t\t<h2 class=\"text-white mb-5\">Subscribe to receive updates!</h2>\r\n");
      out.write("\t\t\t\t\t<form class=\"form-inline d-flex\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"inputEmail\" type=\"email\" placeholder=\"Enter email address...\" />\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary mx-auto\" type=\"submit\">Subscribe</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- Contact-->\r\n");
      out.write("\t<section class=\"contact-section bg-black\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card py-4 h-100\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-map-marked-alt text-primary mb-2\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"text-uppercase m-0\">Address</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<hr class=\"my-4\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"small text-black-50\">4923 Market Street,\r\n");
      out.write("\t\t\t\t\t\t\t\tOrlando FL</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card py-4 h-100\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-envelope text-primary mb-2\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"text-uppercase m-0\">Email</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<hr class=\"my-4\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"small text-black-50\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#!\">hello@yourdomain.com</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card py-4 h-100\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-mobile-alt text-primary mb-2\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"text-uppercase m-0\">Phone</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<hr class=\"my-4\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"small text-black-50\">+1 (555) 902-8832</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"social d-flex justify-content-center\">\r\n");
      out.write("\t\t\t\t<a class=\"mx-2\" href=\"#!\"><i class=\"fab fa-twitter\"></i></a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"mx-2\" href=\"#!\"><i class=\"fab fa-facebook-f\"></i></a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"mx-2\" href=\"#!\"><i class=\"fab fa-github\"></i></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- Footer-->\r\n");
      out.write("\t<footer class=\"footer bg-black small text-center text-white-50\">\r\n");
      out.write("\t\t<div class=\"container\">Copyright Â© Your Website 2020</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- Bootstrap core JS-->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<!-- Third party plugin JS-->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js\"></script>\r\n");
      out.write("\t<!-- Core theme JS-->\r\n");
      out.write("\t<script src=\"js/scripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
